#!/bin/bash

. "${OPENSHIFT_REPO_DIR}.openshift/config/vertx.conf"

cd $OPENSHIFT_DATA_DIR

#Install Vert.x if needed

if [[ -d vert.x-${VERTX_VERSION} ]]; then
	echo "Vert.x ${VERTX_VERSION} already installed."
else
	for version in vert.x-*; do 
		echo "Removing $version"
		rm -rf $version 
	done

	echo "Installing Vert.x $VERTX_VERSION"

  echo "Downloading ${VERTX_DOWNLOAD_URL} ..."
	curl --insecure -o vert.x-${VERTX_VERSION}.tar.gz "${VERTX_DOWNLOAD_URL}"
	tar -xf vert.x-${VERTX_VERSION}.tar.gz
	rm vert.x-${VERTX_VERSION}.tar.gz
fi
